language: node_js
node_js:
  - '11.0.0'
install:
  - npm install
script:
  - npm run lint:styles
  - npm run lint:js
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: dist
  on:
    branch: master
    node: '11.0.0'
